// words.js
export const wordDatabase = [
  { id: "T001", en: "abandon", zh: "放棄；遺棄", pos: "v", length: 7 },
  { id: "T002", en: "abundant", zh: "豐富的；大量的", pos: "adj", length: 8 },
  { id: "T003", en: "access", zh: "接近；通道；使用權", pos: "n", length: 6 },
  { id: "T004", en: "accommodate", zh: "容納；提供住宿", pos: "v", length: 11 },
  { id: "T005", en: "accumulate", zh: "累積；積聚", pos: "v", length: 10 },
  { id: "T006", en: "accurate", zh: "準確的；精確的", pos: "adj", length: 8 },
  { id: "T007", en: "achieve", zh: "達成；實現", pos: "v", length: 7 },
  { id: "T008", en: "acknowledge", zh: "承認；告知收到", pos: "v", length: 11 },
  { id: "T009", en: "acquire", zh: "取得；獲得", pos: "v", length: 7 },
  { id: "T010", en: "adapt", zh: "適應；改編", pos: "v", length: 5 },
  { id: "T011", en: "adequate", zh: "足夠的；適當的", pos: "adj", length: 8 },
  { id: "T012", en: "adjacent", zh: "相鄰的；毗連的", pos: "adj", length: 8 },
  { id: "T013", en: "adjust", zh: "調整；適應", pos: "v", length: 6 },
  { id: "T014", en: "advocate", zh: "提倡；擁護", pos: "v", length: 8 },
  { id: "T015", en: "affect", zh: "影響", pos: "v", length: 6 },
  { id: "T016", en: "aggregate", zh: "總計的；聚集", pos: "adj", length: 9 },
  { id: "T017", en: "allocate", zh: "分配；撥出", pos: "v", length: 8 },
  { id: "T018", en: "alter", zh: "改變；修改", pos: "v", length: 5 },
  { id: "T019", en: "alternative", zh: "替代方案；選擇", pos: "n", length: 11 },
  { id: "T019", en: "alternative", zh: "替代方案；選擇", pos: "n", length: 11 },
  { id: "T020", en: "ambiguous", zh: "模稜兩可的；含糊的", pos: "adj",length: 9 },
  { id: "T021", en: "analyze", zh: "分析", pos: "v", length: 7 },
  { id: "T022", en: "annual", zh: "每年的；年度的", pos: "adj", length: 6 },
  { id: "T023", en: "anticipate", zh: "預期；預料", pos: "v", length: 10 },
  { id: "T024", en: "apparent", zh: "明顯的；表面上的", pos: "adj", length: 8 },
  { id: "T025", en: "appreciate", zh: "欣賞；感激；升值", pos: "v",length: 10 },
  { id: "T026", en: "approach", zh: "方法；接近", pos: "n", length: 8 },
  { id: "T027", en: "appropriate",zh: "適當的；合適的",pos: "adj",length: 11 },
  { id: "T028", en: "approximate",zh: "大約的；近似的",pos: "adj",length: 11 },
  { id: "T029", en: "arbitrary", zh: "任意的；武斷的", pos: "adj", length: 9 },
  { id: "T030", en: "aspect", zh: "方面；層面", pos: "n", length: 6 },
  { id: "T031", en: "assemble", zh: "組裝；集合", pos: "v", length: 8 },
  { id: "T032", en: "assess", zh: "評估；評定", pos: "v", length: 6 },
  { id: "T033", en: "assign", zh: "指派；分配", pos: "v", length: 6 },
  { id: "T034", en: "assist", zh: "協助；幫助", pos: "v", length: 6 },
  { id: "T035", en: "assume", zh: "假定；承擔", pos: "v", length: 6 },
  { id: "T036", en: "assure", zh: "向...保證", pos: "v", length: 6 },
  { id: "T037", en: "attach", zh: "附加；連接", pos: "v", length: 6 },
  { id: "T038", en: "attain", zh: "達到；獲得", pos: "v", length: 6 },
  { id: "T039", en: "attitude", zh: "態度；看法", pos: "n", length: 8 },
  { id: "T040", en: "attribute", zh: "歸因於；特質", pos: "v", length: 9 },
  { id: "T041", en: "author", zh: "作者；創始人", pos: "n", length: 6 },
  { id: "T042", en: "authority", zh: "權威；官方機構", pos: "n", length: 9 },
  { id: "T043", en: "available", zh: "可獲得的；有空的", pos: "adj",length: 9 },
  { id: "T044", en: "aware", zh: "意識到的；知道的", pos: "adj", length: 5 },
  { id: "T045", en: "behalf", zh: "代表；利益", pos: "n", length: 6 },
  { id: "T046", en: "benefit", zh: "利益；好處", pos: "n", length: 7 },
  { id: "T047", en: "bias", zh: "偏見；偏心", pos: "n", length: 4 },
  { id: "T048", en: "bond", zh: "結合；債券", pos: "n", length: 4 },
  { id: "T049", en: "brief", zh: "簡短的；短暫的", pos: "adj", length: 5 },
  { id: "T050", en: "bulk", zh: "大量；體積", pos: "n", length: 4 },
  { id: "T051", en: "ambiguous", zh: "模稜兩可的" },
  { id: "T052", en: "anomaly", zh: "異常現象" },
  { id: "T053", en: "assert", zh: "斷言；主張" },
  { id: "T054", en: "augment", zh: "擴大；增加" },
  { id: "T055", en: "catalyst", zh: "催化劑；促使變化的人事物" },
  { id: "T056", en: "concede", zh: "讓步；承認" },
  { id: "T057", en: "copious", zh: "豐富的；大量的" },
  { id: "T058", en: "corroborate", zh: "證實；確證" },
  { id: "T059", en: "deference", zh: "順從；尊重" },
  { id: "T060", en: "delineate", zh: "描繪；勾勒" },
  { id: "T061", en: "deplete", zh: "消耗；耗盡" },
  { id: "T062", en: "discrepancy", zh: "差異；不一致" },
  { id: "T063", en: "elucidate", zh: "闡明；解釋" },
  { id: "T064", en: "empirical", zh: "經驗主義的；根據實證的" },
  { id: "T065", en: "enigmatic", zh: "神秘的；難以理解的" },
  { id: "T066", en: "ephemeral", zh: "短暫的；朝生暮死的" },
  { id: "T067", en: "equivocal", zh: "含糊其辭的" },
  { id: "T068", en: "exacerbate", zh: "惡化；加劇" },
  { id: "T069", en: "fluctuate", zh: "波動；起伏" },
  { id: "T070", en: "frivolous", zh: "輕浮的；無價值的" },
  { id: "T071", en: "gregarious", zh: "群居的；愛交際的" },
  { id: "T072", en: "hierarchy", zh: "階級制度" },
  { id: "T073", en: "imminent", zh: "即將發生的；逼近的" },
  { id: "T074", en: "implicate", zh: "牽連；暗示" },
  { id: "T075", en: "incentive", zh: "動機；激勵" },
  { id: "T076", en: "indigenous", zh: "本土的；原生的" },
  { id: "T077", en: "inherent", zh: "固有的；與生俱來的" },
  { id: "T078", en: "innocuous", zh: "無害的" },
  { id: "T079", en: "lucid", zh: "清晰的；易懂的" },
  { id: "T080", en: "magnanimous", zh: "寬宏大量的" },
  { id: "T081", en: "mitigate", zh: "減輕；緩和" },
  { id: "T082", en: "novel", zh: "新穎的" },
  { id: "T083", en: "obscure", zh: "模糊的；難解的" },
  { id: "T084", en: "obsolete", zh: "過時的；淘汰的" },
  { id: "T085", en: "paradigm", zh: "典範；範例" },
  { id: "T086", en: "pragmatic", zh: "務實的；實用主義的" },
  { id: "T087", en: "profound", zh: "深遠的；極度的" },
  { id: "T088", en: "prolific", zh: "多產的；豐富的" },
  { id: "T089", en: "redundant", zh: "多餘的；累贅的" },
  { id: "T090", en: "resilient", zh: "有彈性的；適應力強的" },
  { id: "T091", en: "scrutinize", zh: "仔細檢查" },
  { id: "T092", en: "skeptical", zh: "懷疑的" },
  { id: "T093", en: "sporadic", zh: "偶爾發生的；零星的" },
  { id: "T094", en: "stagnant", zh: "停滯的；不景氣的" },
  { id: "T095", en: "substantiate", zh: "證實；證明" },
  { id: "T096", en: "superfluous", zh: "多餘的；過剩的" },
  { id: "T097", en: "tangible", zh: "有形的；實質的" },
  { id: "T098", en: "tenacious", zh: "頑強的；固執的" },
  { id: "T099", en: "ubiquitous", zh: "無所不在的" },
  { id: "T100", en: "vulnerable", zh: "脆弱的；易受傷的" },
  { id: "T101", en: "adversary", zh: "對手；敵手" },
  { id: "T102", en: "advocate", zh: "擁護者；主張" },
  { id: "T103", en: "aesthetic", zh: "美學的；審美的" },
  { id: "T104", en: "altruistic", zh: "利他的；無私的" },
  { id: "T105", en: "benevolent", zh: "仁慈的；慈善的" },
  { id: "T106", en: "bias", zh: "偏見；傾向" },
  { id: "T107", en: "breach", zh: "違背；破裂" },
  { id: "T108", en: "candid", zh: "坦率的；直言不諱的" },
  { id: "T109", en: "capricious", zh: "反覆無常的" },
  { id: "T110", en: "chronicle", zh: "編年史；記錄" },
  { id: "T111", en: "circumspect", zh: "謹慎的；深思熟慮的" },
  { id: "T112", en: "cohesive", zh: "凝聚的；團結的" },
  { id: "T113", en: "collaborate", zh: "合作；協作" },
  { id: "T114", en: "compelling", zh: "引人入勝的；強而有力的" },
  { id: "T115", en: "complement", zh: "補充；補足" },
  { id: "T116", en: "compliance", zh: "服從；遵守" },
  { id: "T117", en: "comprehensive", zh: "全面的；詳盡的" },
  { id: "T118", en: "condone", zh: "寬恕；縱容" },
  { id: "T119", en: "conformity", zh: "符合；一致" },
  { id: "T120", en: "conscientious", zh: "認真的；盡責的" },
  { id: "T121", en: "consensus", zh: "共識；一致同意" },
  { id: "T122", en: "conspicuous", zh: "顯眼的；顯著的" },
  { id: "T123", en: "contemporary", zh: "當代的；同時代的人" },
  { id: "T124", en: "controversial", zh: "有爭議的" },
  { id: "T125", en: "conventional", zh: "傳統的；常規的" },
  { id: "T126", en: "convivial", zh: "歡樂的；好交際的" },
  { id: "T127", en: "cynical", zh: "憤世嫉俗的" },
  { id: "T128", en: "decorum", zh: "端莊；禮節" },
  { id: "T129", en: "denounce", zh: "譴責；指責" },
  { id: "T130", en: "depict", zh: "描繪；描述" },
  { id: "T131", en: "deride", zh: "嘲笑；嘲弄" },
  { id: "T132", en: "devoid", zh: "缺乏的；全無的" },
  { id: "T133", en: "didactic", zh: "教導的；說教的" },
  { id: "T134", en: "diffident", zh: "缺乏自信的；羞怯的" },
  { id: "T135", en: "disdain", zh: "鄙視；輕蔑" },
  { id: "T136", en: "disparate", zh: "迥然不同的" },
  { id: "T137", en: "disseminate", zh: "散佈；傳播" },
  { id: "T138", en: "divergent", zh: "分歧的；發散的" },
  { id: "T139", en: "dogmatic", zh: "武斷的；教條的" },
  { id: "T140", en: "dormant", zh: "休眠的；靜止的" },
  { id: "T141", en: "eccentric", zh: "古怪的；異乎尋常的" },
  { id: "T142", en: "eclectic", zh: "折衷的；來源多樣的" },
  { id: "T143", en: "efficacy", zh: "功效；效驗" },
  { id: "T144", en: "eloquent", zh: "雄辯的；口才流利的" },
  { id: "T145", en: "elusive", zh: "難以捉摸的；躲避的" },
  { id: "T146", en: "emancipate", zh: "解放；釋放" },
  { id: "T147", en: "embellish", zh: "裝飾；修飾" },
  { id: "T148", en: "emulate", zh: "效法；模仿" },
  { id: "T149", en: "endorse", zh: "支持；認可" },
  { id: "T150", en: "enforce", zh: "執行；實施" }
];
