// words.js
export const wordDatabase = [
  { id: "T001", en: "abandon", zh: "放棄；遺棄", pos: "v", length: 7 },
  { id: "T002", en: "abundant", zh: "豐富的；大量的", pos: "adj", length: 8 },
  { id: "T003", en: "access", zh: "接近；通道；使用權", pos: "n", length: 6 },
  { id: "T004", en: "accommodate", zh: "容納；提供住宿", pos: "v", length: 11 },
  { id: "T005", en: "accumulate", zh: "累積；積聚", pos: "v", length: 10 },
  { id: "T006", en: "accurate", zh: "準確的；精確的", pos: "adj", length: 8 },
  { id: "T007", en: "achieve", zh: "達成；實現", pos: "v", length: 7 },
  { id: "T008", en: "acknowledge", zh: "承認；告知收到", pos: "v", length: 11 },
  { id: "T009", en: "acquire", zh: "取得；獲得", pos: "v", length: 7 },
  { id: "T010", en: "adapt", zh: "適應；改編", pos: "v", length: 5 },
  { id: "T011", en: "adequate", zh: "足夠的；適當的", pos: "adj", length: 8 },
  { id: "T012", en: "adjacent", zh: "相鄰的；毗連的", pos: "adj", length: 8 },
  { id: "T013", en: "adjust", zh: "調整；適應", pos: "v", length: 6 },
  { id: "T014", en: "advocate", zh: "提倡；擁護", pos: "v", length: 8 },
  { id: "T015", en: "affect", zh: "影響", pos: "v", length: 6 },
  { id: "T016", en: "aggregate", zh: "總計的；聚集", pos: "adj", length: 9 },
  { id: "T017", en: "allocate", zh: "分配；撥出", pos: "v", length: 8 },
  { id: "T018", en: "alter", zh: "改變；修改", pos: "v", length: 5 },
  { id: "T019", en: "alternative", zh: "替代方案；選擇", pos: "n", length: 11 },
  { id: "T019", en: "alternative", zh: "替代方案；選擇", pos: "n", length: 11 },
  { id: "T020", en: "ambiguous", zh: "模稜兩可的；含糊的", pos: "adj",length: 9 },
  { id: "T021", en: "analyze", zh: "分析", pos: "v", length: 7 },
  { id: "T022", en: "annual", zh: "每年的；年度的", pos: "adj", length: 6 },
  { id: "T023", en: "anticipate", zh: "預期；預料", pos: "v", length: 10 },
  { id: "T024", en: "apparent", zh: "明顯的；表面上的", pos: "adj", length: 8 },
  { id: "T025", en: "appreciate", zh: "欣賞；感激；升值", pos: "v",length: 10 },
  { id: "T026", en: "approach", zh: "方法；接近", pos: "n", length: 8 },
  { id: "T027", en: "appropriate",zh: "適當的；合適的",pos: "adj",length: 11 },
  { id: "T028", en: "approximate",zh: "大約的；近似的",pos: "adj",length: 11 },
  { id: "T029", en: "arbitrary", zh: "任意的；武斷的", pos: "adj", length: 9 },
  { id: "T030", en: "aspect", zh: "方面；層面", pos: "n", length: 6 },
  { id: "T031", en: "assemble", zh: "組裝；集合", pos: "v", length: 8 },
  { id: "T032", en: "assess", zh: "評估；評定", pos: "v", length: 6 },
  { id: "T033", en: "assign", zh: "指派；分配", pos: "v", length: 6 },
  { id: "T034", en: "assist", zh: "協助；幫助", pos: "v", length: 6 },
  { id: "T035", en: "assume", zh: "假定；承擔", pos: "v", length: 6 },
  { id: "T036", en: "assure", zh: "向...保證", pos: "v", length: 6 },
  { id: "T037", en: "attach", zh: "附加；連接", pos: "v", length: 6 },
  { id: "T038", en: "attain", zh: "達到；獲得", pos: "v", length: 6 },
  { id: "T039", en: "attitude", zh: "態度；看法", pos: "n", length: 8 },
  { id: "T040", en: "attribute", zh: "歸因於；特質", pos: "v", length: 9 },
  { id: "T041", en: "author", zh: "作者；創始人", pos: "n", length: 6 },
  { id: "T042", en: "authority", zh: "權威；官方機構", pos: "n", length: 9 },
  { id: "T043", en: "available", zh: "可獲得的；有空的", pos: "adj",length: 9 },
  { id: "T044", en: "aware", zh: "意識到的；知道的", pos: "adj", length: 5 },
  { id: "T045", en: "behalf", zh: "代表；利益", pos: "n", length: 6 },
  { id: "T046", en: "benefit", zh: "利益；好處", pos: "n", length: 7 },
  { id: "T047", en: "bias", zh: "偏見；偏心", pos: "n", length: 4 },
  { id: "T048", en: "bond", zh: "結合；債券", pos: "n", length: 4 },
  { id: "T049", en: "brief", zh: "簡短的；短暫的", pos: "adj", length: 5 },
  { id: "T050", en: "bulk", zh: "大量；體積", pos: "n", length: 4 },
  { id: "T051", en: "ambiguous", zh: "模稜兩可的" },
  { id: "T052", en: "anomaly", zh: "異常現象" },
  { id: "T053", en: "assert", zh: "斷言；主張" },
  { id: "T054", en: "augment", zh: "擴大；增加" },
  { id: "T055", en: "catalyst", zh: "催化劑；促使變化的人事物" },
  { id: "T056", en: "concede", zh: "讓步；承認" },
  { id: "T057", en: "copious", zh: "豐富的；大量的" },
  { id: "T058", en: "corroborate", zh: "證實；確證" },
  { id: "T059", en: "deference", zh: "順從；尊重" },
  { id: "T060", en: "delineate", zh: "描繪；勾勒" },
  { id: "T061", en: "deplete", zh: "消耗；耗盡" },
  { id: "T062", en: "discrepancy", zh: "差異；不一致" },
  { id: "T063", en: "elucidate", zh: "闡明；解釋" },
  { id: "T064", en: "empirical", zh: "經驗主義的；根據實證的" },
  { id: "T065", en: "enigmatic", zh: "神秘的；難以理解的" },
  { id: "T066", en: "ephemeral", zh: "短暫的；朝生暮死的" },
  { id: "T067", en: "equivocal", zh: "含糊其辭的" },
  { id: "T068", en: "exacerbate", zh: "惡化；加劇" },
  { id: "T069", en: "fluctuate", zh: "波動；起伏" },
  { id: "T070", en: "frivolous", zh: "輕浮的；無價值的" },
  { id: "T071", en: "gregarious", zh: "群居的；愛交際的" },
  { id: "T072", en: "hierarchy", zh: "階級制度" },
  { id: "T073", en: "imminent", zh: "即將發生的；逼近的" },
  { id: "T074", en: "implicate", zh: "牽連；暗示" },
  { id: "T075", en: "incentive", zh: "動機；激勵" },
  { id: "T076", en: "indigenous", zh: "本土的；原生的" },
  { id: "T077", en: "inherent", zh: "固有的；與生俱來的" },
  { id: "T078", en: "innocuous", zh: "無害的" },
  { id: "T079", en: "lucid", zh: "清晰的；易懂的" },
  { id: "T080", en: "magnanimous", zh: "寬宏大量的" },
  { id: "T081", en: "mitigate", zh: "減輕；緩和" },
  { id: "T082", en: "novel", zh: "新穎的" },
  { id: "T083", en: "obscure", zh: "模糊的；難解的" },
  { id: "T084", en: "obsolete", zh: "過時的；淘汰的" },
  { id: "T085", en: "paradigm", zh: "典範；範例" },
  { id: "T086", en: "pragmatic", zh: "務實的；實用主義的" },
  { id: "T087", en: "profound", zh: "深遠的；極度的" },
  { id: "T088", en: "prolific", zh: "多產的；豐富的" },
  { id: "T089", en: "redundant", zh: "多餘的；累贅的" },
  { id: "T090", en: "resilient", zh: "有彈性的；適應力強的" },
  { id: "T091", en: "scrutinize", zh: "仔細檢查" },
  { id: "T092", en: "skeptical", zh: "懷疑的" },
  { id: "T093", en: "sporadic", zh: "偶爾發生的；零星的" },
  { id: "T094", en: "stagnant", zh: "停滯的；不景氣的" },
  { id: "T095", en: "substantiate", zh: "證實；證明" },
  { id: "T096", en: "superfluous", zh: "多餘的；過剩的" },
  { id: "T097", en: "tangible", zh: "有形的；實質的" },
  { id: "T098", en: "tenacious", zh: "頑強的；固執的" },
  { id: "T099", en: "ubiquitous", zh: "無所不在的" },
  { id: "T100", en: "vulnerable", zh: "脆弱的；易受傷的" }
];
